const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
test('SQL: owner isolation, media permissions, seed idempotency',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id integer generated always as identity,bucket_id text,name text);
 alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage to anon,authenticated;
 grant select,insert,delete on storage.objects to authenticated;
 grant usage on all sequences in schema storage to authenticated;
 insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
 await db.exec(fs.readFileSync('supabase/setup.sql','utf8'));
 await db.exec(`set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';select public.seed_library_demo();select public.seed_library_demo();`);
 assert.equal((await db.query('select count(*)::int as n from public.library_documents')).rows[0].n,5);
 await db.exec(`insert into storage.objects(bucket_id,name)values('library-media','11111111-1111-4111-8111-111111111111/a.png')`);
 await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name)values('library-media','22222222-2222-4222-8222-222222222222/evil.png')`));
 await db.exec(`set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222'`);
 assert.equal((await db.query('select * from public.library_documents')).rows.length,0);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await assert.rejects(db.exec(`insert into public.library_documents(owner_id,key,payload)values('11111111-1111-4111-8111-111111111111','evil','{}')`));
 await db.exec(`select public.seed_library_demo()`);
 assert.equal((await db.query('select count(*)::int as n from public.library_documents')).rows[0].n,5);
 await db.exec(`reset role;set role anon`);await assert.rejects(db.exec('select public.seed_library_demo()'));await assert.rejects(db.exec('select * from public.library_documents'));
 await db.close();
});
