const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../assets/js/app.js'),'utf8');
function model(scenes,characters=[{id:'a',name:'윤서',baseAge:29}]){const ctx={storyAgeCache:null,state:{characters},charById:id=>characters.find(c=>c.id===id),orderedSceneIds:()=>scenes.map(s=>s.id),codexMatches:(text,c)=>text.includes(c.name)?[[0,1]]:[]};ctx.state.scenes=Object.fromEntries(scenes.map(s=>[s.id,s]));vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('function scenePeriod('),source.indexOf('function ageText(')),ctx);return ctx}
function scene(id,label,characters=['a']){return {id,timelineLabel:label,characters,text:''}}
test('legacy years remain readable and explicit empty periods stay undecided',()=>{const c=model([]);assert.equal(c.scenePeriodLabel({year:2026}),'2026');assert.equal(c.scenePeriodLabel({year:2026,timelineLabel:''}),'시점 미정')});
test('one year is relative, four digit year is absolute; months normalize',()=>{const c=model([]);assert.equal(c.parseStoryPeriod('1년').kind,'relative');assert.equal(c.parseStoryPeriod('2026년').kind,'calendar');assert.equal(c.elapsedPeriod(c.parseStoryPeriod('+1년 +2달').months),'+1년 +2달');assert.equal(c.elapsedPeriod(26),'+2년 +2달');assert.equal(c.parseStoryPeriod('1년 2달 전').months,-14);assert.equal(c.parseStoryPeriod('2026년 13월').kind,'unknown')});
test('relative periods accumulate from story start, even for later characters',()=>{const scenes=[scene('s1','첫 등장',[]),scene('s2','1년 뒤'),scene('s3','2달 뒤')],c=model(scenes);assert.equal(c.characterAgeLabel('a',scenes[1]),'+1년');assert.equal(c.characterAgeLabel('a',scenes[2]),'+1년 +2달');assert.equal(c.scenePeriodLabel(scenes[2]),'+1년 +2달')});
test('calendar years calculate age from the actual first appearance',()=>{const scenes=[scene('s1','2026',[]),scene('s2','2027'),scene('s3','2029')],c=model(scenes);assert.equal(c.characterAgeLabel('a',scenes[2]),'31세')});
test('explicit first year works when the first scene year was undecided',()=>{const scenes=[scene('s1',''),scene('s2','2028년 3월')],c=model(scenes,[{id:'a',name:'윤서',baseAge:29,firstYear:2026}]);assert.equal(c.characterAgeLabel('a',scenes[1]),'31세 2개월')});
test('unknown intermediate periods do not fabricate a cumulative interval',()=>{const scenes=[scene('s1','시작'),scene('s2','어느 날'),scene('s3','1달 뒤')],c=model(scenes);assert.equal(c.characterAgeLabel('a',scenes[1]),'경과 미정');assert.equal(c.characterAgeLabel('a',scenes[2]),'경과 기준 미정')});
test('relative display remains elapsed time after a known calendar year',()=>{const scenes=[scene('s1','2026'),scene('s2','1년 뒤'),scene('s3','2028')],c=model(scenes);assert.equal(c.characterAgeLabel('a',scenes[1]),'+1년');assert.equal(c.characterAgeLabel('a',scenes[2]),'31세')});
test('character name mentions establish an appearance without manual scene links',()=>{const scenes=[scene('s1','2026',[]),{...scene('s2','2027',[]),text:'윤서는 떠났다.'},{...scene('s3','2028',[]),text:'윤서가 돌아왔다.'}],c=model(scenes);assert.equal(c.characterAgeLabel('a',scenes[2]),'30세')});
